[project]
name = "homework"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aio-pika>=9.5.5",
    "aioconsole>=0.8.1",
    "colorama>=0.4.6",
    "prompt-toolkit>=3.0.51",
]
